In [1]:
import numpy as np

def convolve2d(image, kernel, stride=1, padding=0):
    # Lật kernel (convolution = cross-correlation + flip)
    kernel = np.flipud(np.fliplr(kernel))

    # Thêm padding nếu cần
    if padding > 0:
        image = np.pad(image, ((padding, padding), (padding, padding)), mode='constant')

    kernel_height, kernel_width = kernel.shape
    image_height, image_width = image.shape

    # Tính kích thước đầu ra
    out_height = (image_height - kernel_height) // stride + 1
    out_width = (image_width - kernel_width) // stride + 1

    # Khởi tạo đầu ra
    output = np.zeros((out_height, out_width))

    # Tính tích chập
    for y in range(0, out_height):
        for x in range(0, out_width):
            region = image[y*stride:y*stride+kernel_height, x*stride:x*stride+kernel_width]
            output[y, x] = np.sum(region * kernel)

    return output


In [2]:
# Ảnh đầu vào 5x5
image = np.array([
    [1, 2, 0, 1, 3],
    [4, 1, 0, 1, 2],
    [1, 3, 1, 5, 1],
    [6, 2, 1, 4, 0],
    [2, 3, 0, 2, 3]
])

# Kernel lọc Sobel đơn giản (ví dụ)
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Tính tích chập
output = convolve2d(image, kernel, stride=1, padding=1)
print("Output:\n", output)


Output:
 [[  3.  -5.  -1.   5.  -2.]
 [  6.  -5.   1.   5.  -7.]
 [  6.  -9.   4.   1. -10.]
 [  8.  -7.   3.   2. -11.]
 [  5.  -7.   1.   2.  -6.]]
